apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: mypodinfo
        image: stefanprodan/podinfo
        ports:
        - containerPort: 9898
